### ISSUE TITLE
Update mdast to remark

### ISSUE THREAD

**Issue by wooorm** [mapbox/mdast-cross-reference#1]
Hey! Just wanted ping and request a name change from mdast to remark.

Maybe you’ve already seen it but here’s a list of [tips for updating](https://github.com/wooorm/remark/blob/master/doc/plugins.md#renaming-from-mdast-to-remark). And here’s a list of reasons [why to update](https://github.com/wooorm/remark/releases/tag/3.0.0).

Let me know if I can help! :smile:

**Comment by tmcw** [comment]
Merged in https://github.com/mapbox/mdast-cross-reference/pull/2
